# Generated by Django 5.2.1 on 2025-05-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
