# Generated by Django 5.2.1 on 2025-05-18 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storee', '0002_products_productname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yarnType', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=15)),
                ('size', models.CharField(max_length=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storee.products')),
            ],
        ),
    ]
